export const STAR_CATALOG = [
  {
    name: 'Polaris',
    designation: 'α UMi',
    constellation: 'UMi',
    rightAscension: 2.5303,
    declination: 89.2641,
    magnitude: 1.97,
    spectralType: 'F7',
    distance: 447,
    description: 'Étoile polaire actuelle, située presque exactement dans l’axe de rotation terrestre.',
    observation: 'Repère indispensable pour la mise en station d’une monture équatoriale et le cadrage nord.'
  },
  {
    name: 'Dubhe',
    designation: 'α UMa',
    constellation: 'UMa',
    rightAscension: 11.0621,
    declination: 61.7508,
    magnitude: 1.79,
    spectralType: 'K0',
    distance: 123,
    description: 'Étoile orangée marquant le coin supérieur de la Grande Ourse.',
    observation: 'Aligne Dubhe avec Merak pour pointer précisément la Polaire.'
  },
  {
    name: 'Merak',
    designation: 'β UMa',
    constellation: 'UMa',
    rightAscension: 11.0307,
    declination: 56.3824,
    magnitude: 2.37,
    spectralType: 'A1',
    distance: 80,
    description: 'Étoile blanche de la Grande Ourse formant avec Dubhe le repère pour trouver la Polaire.',
    observation: 'La ligne Dubhe → Merak multipliée cinq fois mène directement à Polaris.'
  },
  {
    name: 'Phecda',
    designation: 'γ UMa',
    constellation: 'UMa',
    rightAscension: 11.8987,
    declination: 53.6948,
    magnitude: 2.43,
    spectralType: 'A0',
    distance: 83,
    description: 'Étoile blanche marquant la cuve de la Grande Ourse.',
    observation: 'Servez-vous du trapèze formé par Phecda pour cadrer les galaxies M81/M82.'
  },
  {
    name: 'Megrez',
    designation: 'δ UMa',
    constellation: 'UMa',
    rightAscension: 12.257,
    declination: 57.0326,
    magnitude: 3.31,
    spectralType: 'A3',
    distance: 80,
    description: 'Étoile la plus discrète du chariot mais pivot des segments vers la queue.',
    observation: 'Permet de suivre la courbure menant à Mizar et Alkaid.'
  },
  {
    name: 'Alioth',
    designation: 'ε UMa',
    constellation: 'UMa',
    rightAscension: 12.9005,
    declination: 55.9598,
    magnitude: 1.77,
    spectralType: 'A0',
    distance: 82,
    description: 'Étoile la plus brillante du chariot, visible toute l’année sous nos latitudes.',
    observation: 'Bon point d’ancrage pour balayer la région des galaxies du Bouvier.'
  },
  {
    name: 'Mizar',
    designation: 'ζ UMa',
    constellation: 'UMa',
    rightAscension: 13.3987,
    declination: 54.9253,
    magnitude: 2.23,
    spectralType: 'A2',
    distance: 86,
    description: 'Étoile double emblématique, facilement résolue aux jumelles avec Alcor.',
    observation: 'Test de pouvoir séparateur classique pour un instrument bien collimaté.'
  },
  {
    name: 'Alkaid',
    designation: 'η UMa',
    constellation: 'UMa',
    rightAscension: 13.7923,
    declination: 49.3133,
    magnitude: 1.85,
    spectralType: 'B3',
    distance: 104,
    description: 'Dernière étoile de la queue de la Grande Ourse, bleutée et énergique.',
    observation: 'Dirige ton regard vers le quadrilatère du Bouvier depuis Alkaid pour trouver Arcturus.'
  },
  {
    name: 'Kochab',
    designation: 'β UMi',
    constellation: 'UMi',
    rightAscension: 14.8451,
    declination: 74.1555,
    magnitude: 2.08,
    spectralType: 'K4',
    distance: 131,
    description: 'L’une des deux gardiennes du pôle entourant Polaris.',
    observation: 'Aligne Kochab avec Pherkad pour visualiser le petit chariot.'
  },
  {
    name: 'Pherkad',
    designation: 'γ UMi',
    constellation: 'UMi',
    rightAscension: 15.3455,
    declination: 71.8339,
    magnitude: 3.05,
    spectralType: 'A3',
    distance: 487,
    description: 'Étoile bleutée complétant la poignée du Petit Chariot.',
    observation: 'Forme avec Kochab un axe pratique pour vérifier la mise en station.'
  },
  {
    name: 'Vega',
    designation: 'α Lyr',
    constellation: 'Lyr',
    rightAscension: 18.6156,
    declination: 38.7837,
    magnitude: 0.03,
    spectralType: 'A0',
    distance: 25,
    description: 'Astre phare du ciel d’été, proche du zénith sous nos latitudes.',
    observation: 'Point de départ idéal pour repérer la Lyre et la nébuleuse annulaire M57.'
  },
  {
    name: 'Sheliak',
    designation: 'β Lyr',
    constellation: 'Lyr',
    rightAscension: 18.8346,
    declination: 33.3627,
    magnitude: 3.45,
    spectralType: 'B7',
    distance: 960,
    description: 'Binaire à éclipses représentant la base de la Lyre.',
    observation: 'Observe ses variations de luminosité sur plusieurs nuits claires.'
  },
  {
    name: 'Sulafat',
    designation: 'γ Lyr',
    constellation: 'Lyr',
    rightAscension: 18.9826,
    declination: 32.6896,
    magnitude: 3.25,
    spectralType: 'B9',
    distance: 620,
    description: 'Étoile bleue formant l’angle opposé à Vega dans la Lyre.',
    observation: 'Centre-toi entre Sulafat et Sheliak pour viser M57.'
  },
  {
    name: 'Deneb',
    designation: 'α Cyg',
    constellation: 'Cyg',
    rightAscension: 20.6905,
    declination: 45.2803,
    magnitude: 1.25,
    spectralType: 'A2',
    distance: 2616,
    description: 'Supergéante blanche marquant la queue du Cygne.',
    observation: 'Encadre Deneb avec Sadr et Gienah pour suivre la grande croix du Cygne.'
  },
  {
    name: 'Sadr',
    designation: 'γ Cyg',
    constellation: 'Cyg',
    rightAscension: 20.3705,
    declination: 40.2567,
    magnitude: 2.23,
    spectralType: 'F8',
    distance: 1830,
    description: 'Cœur de la constellation du Cygne baignant dans la Voie lactée.',
    observation: 'Balaye autour de Sadr pour révéler IC 1318 et les nébulosités de Gamma Cygni.'
  },
  {
    name: 'Gienah',
    designation: 'ε Cyg',
    constellation: 'Cyg',
    rightAscension: 20.77,
    declination: 33.9703,
    magnitude: 2.48,
    spectralType: 'B9',
    distance: 72,
    description: 'Aile occidentale du Cygne, étoile double accessible.',
    observation: 'Parfaite pour tester la résolution d’une petite lunette.'
  },
  {
    name: 'Albireo',
    designation: 'β Cyg',
    constellation: 'Cyg',
    rightAscension: 19.512,
    declination: 27.9597,
    magnitude: 3.08,
    spectralType: 'K3 + B8',
    distance: 430,
    description: 'Étoile double célèbre pour son contraste orange/bleu.',
    observation: 'Augmente légèrement le grossissement pour séparer les deux composantes chatoyantes.'
  },
  {
    name: 'Altair',
    designation: 'α Aql',
    constellation: 'Aql',
    rightAscension: 19.8464,
    declination: 8.8683,
    magnitude: 0.77,
    spectralType: 'A7',
    distance: 17,
    description: 'Étoile brillante du Triangle d’été, très rapide en rotation.',
    observation: 'Trace la ligne Altair–Vega pour rejoindre le zénith en été.'
  },
  {
    name: 'Tarazed',
    designation: 'γ Aql',
    constellation: 'Aql',
    rightAscension: 19.7705,
    declination: 10.6132,
    magnitude: 2.72,
    spectralType: 'K3',
    distance: 395,
    description: 'Géante orangée voisinant Altair dans Aquila.',
    observation: 'Offre un joli contraste de couleur avec Altair et Alshain.'
  },
  {
    name: 'Alshain',
    designation: 'β Aql',
    constellation: 'Aql',
    rightAscension: 19.9219,
    declination: 6.4068,
    magnitude: 3.71,
    spectralType: 'G8',
    distance: 45,
    description: 'Compagne plus discrète d’Altair, étoile double accessible.',
    observation: 'Un grossissement modéré révèle la compagne Alshain B.'
  },
  {
    name: 'Betelgeuse',
    designation: 'α Ori',
    constellation: 'Ori',
    rightAscension: 5.9195,
    declination: 7.407,
    magnitude: 0.5,
    spectralType: 'M1',
    distance: 548,
    description: 'Supergéante rouge en fin de vie, très variable.',
    observation: 'Comparatif de luminosité avec Rigel pour suivre ses variations.'
  },
  {
    name: 'Bellatrix',
    designation: 'γ Ori',
    constellation: 'Ori',
    rightAscension: 5.4188,
    declination: 6.3497,
    magnitude: 1.64,
    spectralType: 'B2',
    distance: 252,
    description: 'Guerrière brillante marquant l’épaule droite d’Orion.',
    observation: 'Servez-vous de Bellatrix pour cadrer la boucle de Barnard.'
  },
  {
    name: 'Mintaka',
    designation: 'δ Ori',
    constellation: 'Ori',
    rightAscension: 5.5334,
    declination: -0.2991,
    magnitude: 2.25,
    spectralType: 'O9',
    distance: 1200,
    description: 'Étoile occidentale de la ceinture d’Orion, double serrée.',
    observation: 'Bon test de turbulence : la composante secondaire devient visible par nuit stable.'
  },
  {
    name: 'Alnilam',
    designation: 'ε Ori',
    constellation: 'Ori',
    rightAscension: 5.6036,
    declination: -1.2019,
    magnitude: 1.69,
    spectralType: 'B0',
    distance: 1342,
    description: 'Étoile centrale de la ceinture d’Orion, entourée de poussières.',
    observation: 'Viser Alnilam en photo révèle la nébuleuse de la Tête de Cheval à proximité.'
  },
  {
    name: 'Alnitak',
    designation: 'ζ Ori',
    constellation: 'Ori',
    rightAscension: 5.6793,
    declination: -1.9426,
    magnitude: 1.74,
    spectralType: 'O9',
    distance: 817,
    description: 'Étoile orientale de la ceinture, triple spectaculaire.',
    observation: 'Centre la flamme d’Orion (NGC 2024) à quelques minutes d’arc vers l’est.'
  },
  {
    name: 'Rigel',
    designation: 'β Ori',
    constellation: 'Ori',
    rightAscension: 5.2423,
    declination: -8.2016,
    magnitude: 0.18,
    spectralType: 'B8',
    distance: 863,
    description: 'Supergéante bleue dominant l’hémisphère sud hivernal.',
    observation: 'Pousse le grossissement pour séparer la compagne Rigel B.'
  },
  {
    name: 'Saiph',
    designation: 'κ Ori',
    constellation: 'Ori',
    rightAscension: 5.7959,
    declination: -9.6696,
    magnitude: 2.06,
    spectralType: 'B0',
    distance: 650,
    description: 'Coin sud-est d’Orion, marque la limite de la boucle d’Orion.',
    observation: 'Repère pour encadrer la nébuleuse de la Rosette plus à l’est.'
  },
  {
    name: 'Sirius',
    designation: 'α CMa',
    constellation: 'CMa',
    rightAscension: 6.7525,
    declination: -16.7161,
    magnitude: -1.46,
    spectralType: 'A1',
    distance: 8.6,
    description: 'Étoile la plus brillante du ciel nocturne, visible même en ville.',
    observation: 'Attends qu’elle culmine pour tenter d’apercevoir sa naine blanche compagne.'
  },
  {
    name: 'Adhara',
    designation: 'ε CMa',
    constellation: 'CMa',
    rightAscension: 6.9771,
    declination: -28.9721,
    magnitude: 1.5,
    spectralType: 'B2',
    distance: 430,
    description: 'Deuxième étoile de la constellation du Grand Chien.',
    observation: 'Constitue avec Wezen un triangle pointant vers M41.'
  },
  {
    name: 'Wezen',
    designation: 'δ CMa',
    constellation: 'CMa',
    rightAscension: 7.1399,
    declination: -26.3932,
    magnitude: 1.82,
    spectralType: 'F8',
    distance: 1600,
    description: 'Supergéante jaune marquant le centre du Grand Chien.',
    observation: 'Base idéale pour localiser la nébuleuse de la Rosette en remontant vers Monoceros.'
  },
  {
    name: 'Procyon',
    designation: 'α CMi',
    constellation: 'CMi',
    rightAscension: 7.655,
    declination: 5.225,
    magnitude: 0.38,
    spectralType: 'F5',
    distance: 11.5,
    description: 'Une des composantes du Triangle d’hiver, proche de la Terre.',
    observation: 'Combine Procyon avec Sirius et Betelgeuse pour dessiner le triangle hivernal.'
  },
  {
    name: 'Capella',
    designation: 'α Aur',
    constellation: 'Aur',
    rightAscension: 5.2782,
    declination: 46.0,
    magnitude: 0.08,
    spectralType: 'G3',
    distance: 42,
    description: 'Système quadruple dominant l’hiver boréal.',
    observation: 'Utilise Capella pour t’orienter vers l’amas des Hyades.'
  },
  {
    name: 'Aldebaran',
    designation: 'α Tau',
    constellation: 'Tau',
    rightAscension: 4.5987,
    declination: 16.5092,
    magnitude: 0.87,
    spectralType: 'K5',
    distance: 65,
    description: 'Géante orangée traversant l’amas ouvert des Hyades.',
    observation: 'Filtre UHC déconseillé : privilégie un oculaire grand champ pour les Hyades.'
  },
  {
    name: 'Elnath',
    designation: 'β Tau',
    constellation: 'Tau',
    rightAscension: 5.4382,
    declination: 28.6074,
    magnitude: 1.65,
    spectralType: 'B7',
    distance: 134,
    description: 'Étoile bleutée à la frontière du Cocher et du Taureau.',
    observation: 'Aide à tracer la corne nord du Taureau vers la nébuleuse du Crabe.'
  },
  {
    name: 'Castor',
    designation: 'α Gem',
    constellation: 'Gem',
    rightAscension: 7.5767,
    declination: 31.8883,
    magnitude: 1.6,
    spectralType: 'A1',
    distance: 52,
    description: 'Sextuple système stellaire facilement dédoublable.',
    observation: 'Grossissement moyen pour séparer les composantes A et B.'
  },
  {
    name: 'Pollux',
    designation: 'β Gem',
    constellation: 'Gem',
    rightAscension: 7.7553,
    declination: 28.0262,
    magnitude: 1.14,
    spectralType: 'K0',
    distance: 34,
    description: 'Géante orangée abritant une exoplanète confirmée.',
    observation: 'Une paire parfaite avec Castor pour débuter les repérages hivernaux.'
  },
  {
    name: 'Regulus',
    designation: 'α Leo',
    constellation: 'Leo',
    rightAscension: 10.1395,
    declination: 11.9672,
    magnitude: 1.35,
    spectralType: 'B7',
    distance: 79,
    description: 'Étoile principale du Lion alignée avec le Sphinx céleste.',
    observation: 'Utilise Regulus pour balayer la chaîne de galaxies de l’arrière du Lion.'
  },
  {
    name: 'Algieba',
    designation: 'γ Leo',
    constellation: 'Leo',
    rightAscension: 10.3329,
    declination: 19.8416,
    magnitude: 2.01,
    spectralType: 'K1',
    distance: 130,
    description: 'Magnifique double dorée dans la crinière du Lion.',
    observation: 'Sépare les composantes avec un grossissement supérieur à 120×.'
  },
  {
    name: 'Denebola',
    designation: 'β Leo',
    constellation: 'Leo',
    rightAscension: 11.8177,
    declination: 14.5719,
    magnitude: 2.14,
    spectralType: 'A3',
    distance: 36,
    description: 'Queue du Lion, marque l’accès au Champ de Coma.',
    observation: 'Prolonge la ligne Zosma–Denebola pour atteindre l’amas de la Chevelure.'
  },
  {
    name: 'Arcturus',
    designation: 'α Boo',
    constellation: 'Boo',
    rightAscension: 14.261,
    declination: 19.1825,
    magnitude: -0.05,
    spectralType: 'K1',
    distance: 36,
    description: 'Géante orangée visible en fin de printemps, se lève après la Grande Ourse.',
    observation: 'Prolonge la courbure de la queue de la Grande Ourse pour atteindre Arcturus.'
  },
  {
    name: 'Spica',
    designation: 'α Vir',
    constellation: 'Vir',
    rightAscension: 13.4199,
    declination: -11.1614,
    magnitude: 0.98,
    spectralType: 'B1',
    distance: 250,
    description: 'Binaire spectroscopique bleu-blanc marquant la Vierge.',
    observation: 'Trace Arcturus → Spica pour localiser la Vierge et ses galaxies.'
  },
  {
    name: 'Antares',
    designation: 'α Sco',
    constellation: 'Sco',
    rightAscension: 16.4901,
    declination: -26.4319,
    magnitude: 1.06,
    spectralType: 'M1',
    distance: 555,
    description: 'Supergéante rouge flamboyante au cœur du Scorpion.',
    observation: 'Compare sa teinte rouge à celle de Mars lors des oppositions.'
  },
  {
    name: 'Shaula',
    designation: 'λ Sco',
    constellation: 'Sco',
    rightAscension: 17.5601,
    declination: -37.1038,
    magnitude: 1.62,
    spectralType: 'B2',
    distance: 570,
    description: 'Étoile bleutée marquant le dard du Scorpion.',
    observation: 'Cadre la région pour révéler l’amas ouvert M7.'
  },
  {
    name: 'Sargas',
    designation: 'θ Sco',
    constellation: 'Sco',
    rightAscension: 17.6219,
    declination: -42.9978,
    magnitude: 1.86,
    spectralType: 'F0',
    distance: 270,
    description: 'Supergéante jaune du Scorpion austral.',
    observation: 'Accueille les nébulosités de la région de la queue du Scorpion.'
  },
  {
    name: 'Fomalhaut',
    designation: 'α PsA',
    constellation: 'PsA',
    rightAscension: 22.9608,
    declination: -29.6222,
    magnitude: 1.16,
    spectralType: 'A4',
    distance: 25,
    description: 'Étoile solitaire de l’automne, hôte d’un disque protoplanétaire.',
    observation: 'Choisis un horizon dégagé vers le sud pour la saisir.'
  },
  {
    name: 'Achernar',
    designation: 'α Eri',
    constellation: 'Eri',
    rightAscension: 1.6286,
    declination: -57.2368,
    magnitude: 0.46,
    spectralType: 'B6',
    distance: 139,
    description: 'Étoile aplatie très rapide, visible près de l’horizon sud.',
    observation: 'Observation difficile depuis la France métropolitaine : privilégie les nuits sans turbulence.'
  },
  {
    name: 'Canopus',
    designation: 'α Car',
    constellation: 'Car',
    rightAscension: 6.3992,
    declination: -52.6957,
    magnitude: -0.62,
    spectralType: 'F0',
    distance: 310,
    description: 'Deuxième étoile la plus brillante du ciel, réservée aux latitudes méridionales.',
    observation: 'Accessible depuis le sud de l’Europe lors de conditions exceptionnelles.'
  }
];

